backend/instarDjango/history/urls.py
from django.urls import path

from . import views

app_name = 'history'
urlpatterns = [
    # ex. /people/
    path('', views.index, name='index'),
    # ex. /people/5/
    path('<int:event_id>/', views.detail, name="detail"),
]

backend/instarDjango/instarDjango/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('people/', include('people.urls')),
    path('map/', include('map.urls')),
    path('history/', include('history.urls')),
    path('admin/', admin.site.urls),
]

backend/instarDjango/map/urls.py
from django.urls import path

from . import views

app_name = 'map'
urlpatterns = [
    # ex. /people/
    path('', views.map, name='map'),
    # ex. /people/5/
]

backend/instarDjango/people/urls.py
from django.urls import path

from . import views

app_name = 'people'
urlpatterns = [
    # ex. /people/
    path('', views.index, name='index'),
    # ex. /people/5/
    path('<int:character_id>/', views.detail, name="detail"),

    path('<int:character_id>/submitNote', views.submitNote, name="note"),

    path('notes/<int:note_id>/delete', views.deleteNote, name="delNote")
]

backend/instarDjango/history/models.py
from django.db import models

# Create your models here.
class Campaign(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Event(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=200)
    time = models.DateField()
    description = models.CharField(max_length=3000)
    def __str__(self):
        return self.name

backend/instarDjango/map/models.py
from django.db import models

# Create your models here.
class Campaign(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Body(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=200)
    imageUrl = models.URLField(max_length=200, default="https://cdn.discordapp.com/attachments/432564281113051136/952994827543404574/1355328252_2.gif")
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)
    x = models.FloatField(default=0)
    y = models.FloatField(default=0)
    def __str__(self):
        return self.name
    def to_json(self):
        return {
            'name': self.name,
            'imageUrl': self.imageUrl,
            'parent': self.parent,
        }

backend/instarDjango/people/models.py
from django.db import models

# Create your models here.
class Campaign(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Character(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Note(models.Model):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    note_text = models.CharField(max_length=400)
    def __str__(self):
        return self.note_text

backend/instarDjango/history/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render
from django.urls import reverse
from .models import Event, Campaign


def index(request):
    c=request.GET.get('c','1')
    event_list = Event.objects.filter(campaign=c).order_by('-time')
    campaign_list = Campaign.objects.all()
    context = {
        'campaign_list': campaign_list,
        'event_list': event_list,
    }
    return render(request,'history/index.html',context)

def detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id); 
    return render(request, 'history/detail.html', {'event':event})

backend/instarDjango/instarDjango/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render

def index(request):
    return render(request, "people/home.html", {})

backend/instarDjango/map/views.py
from json import JSONEncoder
import json
from django.shortcuts import render
from .models import Body

def map(request):
    body_list = Body.objects.all()

    context = {
        'body_list': body_list,
        
    }
    return render(request,'map/map.html',context)

backend/instarDjango/people/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render
from django.urls import reverse
from .models import Character, Note, Campaign


def index(request):
    c=request.GET.get('c','1')
    campaign_list = Campaign.objects.all()
    character_list = Character.objects.filter(campaign=c).order_by('-name')[::-1]
    context = {
        'character_list': character_list,
        'campaign_list': campaign_list,
    }
    return render(request,'people/index.html',context)

def detail(request, character_id):
    character = get_object_or_404(Character, pk=character_id)
    notes_list = Note.objects.filter(character=character)
    return render(request, 'people/detail.html', {'character':character, 'notes_list':notes_list})

def submitNote(request, character_id):
    character = get_object_or_404(Character, pk=character_id)
    new_note = Note(character = character, note_text = request.POST['note'])
    new_note.save()
    return HttpResponseRedirect(reverse('people:detail', args=(character_id,)))

def deleteNote(request, note_id):
    if request.method == 'POST':

        note = get_object_or_404(Note, pk=note_id)
        character = note.character

        note.delete()
        return HttpResponse(status='200', content={"success": True})
    return HttpResponseRedirect(reverse('people:detail', args=(character.id,)))

backend/instarDjango/history/templates/history/detail.html
<html>
    <head>
        <title> Instar OS</title>
        <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
    </head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <body>

        <div class="instarlogo">Instar OS</div>
        <script src="{% static 'js/logo.js' %}"></script>

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="../..">Home</a></li>
              <li class="breadcrumb-item"><a href="..">History</a></li>
              <li class="breadcrumb-item active" aria-current="page"> {{ event.name }}</li>
            </ol>
          </nav>

        <section id="event">
          <h2> {{ event.name}} </h2>
          <h4> {{ event.time }} </h4> 
          <p> {{event.description}} </p>
        </section>

    </body>
</html>

backend/instarDjango/history/templates/history/index.html
    <html>
    <head>
        <title> Instar OS</title>
        <script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
    </head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <body>
        
        <div class="instarlogo">Instar OS</div>
        <script src="{% static 'js/logo.js' %}"></script>
        
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="..">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page"> History </li>
            </ol>
        </nav>

        <div class="container">
            {% for campaign in campaign_list%}
            <a href="?c={{campaign.id}}">
                <button type="button" class="btn btn-primary"> {{campaign.name}} </button>
            </a>
            {%endfor%}
        </div>
        
        
        <section id="timeline">
            {% if event_list %}
            <div class="list-group">
                <ul>
                    {% for event in event_list %}
                    
                    <li><a href="{% url 'history:detail' event.id %}" class="char_list">{{ event.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            {% else %}
            <p>No events.</p>
            {% endif %}
        </section>
    </body>
    </html>
 

backend/instarDjango/instarDjango/templates/home/index.html
<html>
    <head>
        <title> Instar OS</title>
        <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
    </head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <body>

        <div class="instarlogo">Instar OS</div>
        <script src="{% static 'js/logo.js' %}"></script>

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="../..">Home</a></li>
              <li class="breadcrumb-item"><a href="..">Characters</a></li>
              <li class="breadcrumb-item active" aria-current="page"> {{ character.name }}</li>
            </ol>
          </nav>

    </body>
</html>

backend/instarDjango/map/templates/map/map.html
<html>
<head>
    <title> Instar OS - Map </title>
    <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
    <script src="https://cdn.anychart.com/releases/8.8.0/js/anychart-core.min.js"></script>
    <script src="https://cdn.anychart.com/releases/8.8.0/js/anychart-graph.min.js"></script>
    <script src="https://cdn.anychart.com/releases/8.8.0/js/anychart-data-adapter.min.js"></script>
</head>
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
<link rel="stylesheet" href="{% static 'css/style.css' %}">  
<body>
    
    <div class="instarlogo">Instar OS --------------------</div>
    
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="..">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page"> Map </li>
        </ol>
    </nav>
    
    <div class="row" >
        <div class="col-md-8" height="flex" style="overflow:shown;">
            <div id="container" style="height: 500px;">
                <button onclick='chartType()' type="button" class="btn btn-primary">Switch View</button>
                <script type="text/javascript">
                    
                    // create data
                    var body_list = [
                    {% for body in body_list %}
                    '{{body.name}}',
                    {%endfor%}
                    ]
                    var body_image_list = [
                    {% for body in body_list %}
                    '{{body.imageUrl}}',
                    {%endfor%}
                    ]
                    var body_parent_list = [
                    {% for body in body_list %}
                    '{{body.parent}}',
                    {%endfor%}
                    ]
                    var body_x_list = [
                    {% for body in body_list %}
                    {{body.x}},
                    
                    {%endfor%}
                    ]
                    var body_y_list = [
                    {% for body in body_list %}
                    {{body.y}},
                    {%endfor%}
                    ]

                    var data = {
                        
                        nodes: [
                        // {id: "{{planets}}", x:   0, y: 100},
                        
                        ],
                        edges: [
                        //{from: "Sol", to: "The Bleeding Sun"},
                        ]
                    };
                    for(i = 0; i < body_list.length; i++){
                        data.nodes.push({id: body_list[i], fill: {src: body_image_list[i]}, x: body_x_list[i], y: body_y_list[i]})
                    }
                    for(i = 0; i < body_list.length; i++){
                        if (body_list[i] == "Ender"){
                            var j = Math.floor(Math.random()*body_list.length)
                            data.edges.push({from:"Ender", to:body_list[j]});
                            data.nodes[i].x = body_x_list[j];
                            data.nodes[i].y = body_y_list[j]+30;
                        } 
                        if (body_parent_list[i] != 'None'){
                            data.edges.push({from:body_parent_list[i], to:body_list[i]})
                        }
                    }
                    var chart = anychart.graph(data);
                    // set the title
                    chart.title("");
                    chart.background().stroke({
                        color: "#222",
                        thickness: 2,
                    })
                    

                    chart.edges().selected().stroke("#222", 2);
                    //chart.background().fill("#333");
                    chart.background().fill({
                        src: "https://i.imgur.com/sGcm6DX.png",
                        mode: "tile"
                        });
                    // draw the chart
                    chart.container("container");
                    chart.draw();
                    function chartType(){
                        if (chart.layout().type() == "forced") chart.layout().type("fixed");
                        else chart.layout().type("forced");
                    }
                    // add a listener
                    chart.listen('click', function(e){
                        var tag = e.domTarget.tag;
                        if (tag) {
                            
                            if (tag.type === 'node') {
                                // get url from data directly
                                var url;
                                for (var i = 0; i < data.nodes.length; i++) {
                                    if (data.nodes[i].id === tag.id) {
                                        document.getElementById("moreInfoName").textContent = data.nodes[i].id
                                        document.getElementById("moreInfoImg").src = body_image_list[i]
                                        break;
                                    }
                                }
                                
                            }
                        }
                    });
                    
                    
                </script>
            </div>
        </div>
        <div class="col-md-3">
            <h2 id="moreInfoName">
                Earth
            </h2>
            <img src="https://cdn.discordapp.com/attachments/432564281113051136/952995078912241674/819133564.gif" 
                alt="Body_image" style="width:96px;height:96px;" id="moreInfoImg">
            <p id="moreInfoDesc">
                
            </p>
        </div>
        
    </div>
    
</body>
</html>

backend/instarDjango/people/templates/people/delnote.html
<html>
    <head>
        <title> Instar OS</title>
        <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
    </head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <body>

        <div class="instarlogo">Instar OS</div>
        <script src="{% static 'js/logo.js' %}"></script>

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="../..">Home</a></li>
              <li class="breadcrumb-item"><a href="..">Characters</a></li>
              <li class="breadcrumb-item active" aria-current="page"> Note {{ note.id }}</li>
            </ol>
          </nav>

        <section id="character">
          <h2> {{note.note_text}} </h2>
        </section>


        <form action="{% url 'people:note' character.id %}" method="post">
          {% csrf_token %}
            <div class="mb-3">
              <label for="exampleFormControlTextarea1" class="form-label">Note Description</label>
              <textarea class="form-control" name='note' rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Add Note</button>
          </form>

    </body>
</html>

backend/instarDjango/people/templates/people/detail.html
<html>
    <head>
        <title> Instar OS</title>
        <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
    </head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <body>

        <div class="instarlogo">Instar OS</div>
        <script src="{% static 'js/logo.js' %}"></script>

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="../..">Home</a></li>
              <li class="breadcrumb-item"><a href="..">Characters</a></li>
              <li class="breadcrumb-item active" aria-current="page"> {{ character.name }}</li>
            </ol>
          </nav>

        <section id="character">
          <h2> {{ character.name}} </h2>
        </section>
        <script language="javascript"> 

          function DoPost(id){
             // $.post("../notes/" + id + "/delete", { name: "Delete" } );
             $.ajax({
              url : "../notes/" + id + "/delete",
              type: "POST",
              data : {name: "Delete", csrfmiddlewaretoken: "{{csrf_token}}"},
              dataType : "json",
              complete: function( data ){
                window.location.reload();
              }
              
          });
          
          }
       
       </script>
       

        <div class="list-group">
          <ul>
              {% for note in notes_list %}

              <li class = 'notes_list'>{{ note.note_text }} <a href="Javascript:DoPost({{note.id}})"><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16" style="float: right">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
              </svg></a></li>
              {% endfor %}
          </ul>
      </div>

        <form action="{% url 'people:note' character.id %}" method="post">
          {% csrf_token %}
            <div class="mb-3">
              <label for="exampleFormControlTextarea1" class="form-label">Note Description</label>
              <textarea class="form-control" name='note' rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Add Note</button>
          </form>

    </body>
</html>

backend/instarDjango/people/templates/people/home.html
<html>
    <head>
        <title> Instar OS</title>
        <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
    </head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <body>

        <div class="instarlogo">Instar OS</div>
        <script src="{% static 'js/logo.js' %}"></script>

        <div class="row">
            <div class="col-sm-3">
              <div class="card" style="background-color: #222;">
                <div class="card-body" >
                    <h2><svg xmlns="http://www.w3.org/2000/svg" width="64px" height="64px" fill="currentColor" class="bi bi-map" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M15.817.113A.5.5 0 0 1 16 .5v14a.5.5 0 0 1-.402.49l-5 1a.502.502 0 0 1-.196 0L5.5 15.01l-4.902.98A.5.5 0 0 1 0 15.5v-14a.5.5 0 0 1 .402-.49l5-1a.5.5 0 0 1 .196 0L10.5.99l4.902-.98a.5.5 0 0 1 .415.103zM10 1.91l-4-.8v12.98l4 .8V1.91zm1 12.98 4-.8V1.11l-4 .8v12.98zm-6-.8V1.11l-4 .8v12.98l4-.8z"/>
                      </svg></h2>
                  <h5 class="card-title">Interactive Map</h5>
                  <p class="card-text"></p>
                  <a href="/map/" class="btn btn-primary">Launch</a>
                </div>
              </div>
            </div>
            <div class="col-sm-3">
              <div class="card"style="background-color: #222;">
                <div class="card-body">
                    <h2><svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                        <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                      </svg></h2>
                  <h5 class="card-title">People</h5>
                  <p class="card-text"></p>
                  <a href="/people/" class="btn btn-primary">Launch</a>
                </div>
              </div>
            </div>
            <div class="col-sm-3">
                <div class="card"style="background-color: #222;">
                  <div class="card-body">
                    <h2><svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-watch" viewBox="0 0 16 16">
                        <path d="M8.5 5a.5.5 0 0 0-1 0v2.5H6a.5.5 0 0 0 0 1h2a.5.5 0 0 0 .5-.5V5z"/>
                        <path d="M5.667 16C4.747 16 4 15.254 4 14.333v-1.86A5.985 5.985 0 0 1 2 8c0-1.777.772-3.374 2-4.472V1.667C4 .747 4.746 0 5.667 0h4.666C11.253 0 12 .746 12 1.667v1.86a5.99 5.99 0 0 1 1.918 3.48.502.502 0 0 1 .582.493v1a.5.5 0 0 1-.582.493A5.99 5.99 0 0 1 12 12.473v1.86c0 .92-.746 1.667-1.667 1.667H5.667zM13 8A5 5 0 1 0 3 8a5 5 0 0 0 10 0z"/>
                      </svg></h2>
                    <h5 class="card-title">History</h5>
                    <p class="card-text"></p>
                    <a href="/history/" class="btn btn-primary">Launch</a>
                  </div>
                </div>
              </div>
          </div>


    </body>
</html>